### ISSUE TITLE
Clip package

### ISSUE THREAD

**Issue by lcwyylcwyy** [IGLICT/NeRFFaceEditing#1]
Hi I got:
Could not find a version that satisfies the requirement clip==1.0
currently, the latest version clip is 0.2.0, could tell me which clip repo or package is in the enviroment.xml?

**Comment by RaymondJiangkw** [comment]
Hi, 

Thanks for your interest on our work. The clip package refers to this [repository](https://github.com/openai/CLIP).

You can follow the installation instruction provided in their repo.

Best

**Comment by lcwyylcwyy** [comment]
Thanks a lot!
