### ISSUE TITLE
Training script

### ISSUE THREAD

**Issue by youngAt19** [IGLICT/NeRFFaceEditing#2]
Hi, thanks for sharing your work.
I am trying to understand the training process.
Would the training scripts be released soon?

**Comment by RaymondJiangkw** [comment]
Hi, thanks for your interest on our work.

We have implemented our framework on the official EG3D with a few modifications. The training script will be released along with the version implemented on the official EG3D. Such release is expected soon. :)

**Comment by youngAt19** [comment]
Thank you~

**Comment by youngAt19** [comment]
@RaymondJiangkw Hi, in the supplementary material you mentioned that the weights for histogram loss are different for different parts. How do you set the weights in your experiment?

**Comment by RaymondJiangkw** [comment]
Hi, the training details will be released along with the implementation on the official EG3D. 
I have cleaned and prepared the code several days ago, but I do not know when the code will be released. :)

**Comment by youngAt19** [comment]
Thanks a lot.

**Comment by RaymondJiangkw** [comment]
Hi, the code implemented on the official EG3D has been released. The training has been modified as adversarial for quality. However, the histogram and semantic mask regularizations are retained.

You can find the details at [here](https://github.com/IGLICT/NeRFFaceEditing/blob/updated/training/loss.py).
