### ISSUE TITLE
Style Transfer with real images

### ISSUE THREAD

**Issue by johnberg1** [IGLICT/NeRFFaceEditing#3]
Hi, thank you very much for your great work. I wanted to do style transfer using real images but I see from your inference notebook that you only included style transfer experiments where the inputs are sampled as latents. Furthermore, the latents in the W+ space are of shape [1, 19, 512], therefore standard StyleGAN2 inversion networks like e4e or ReStyle Encoder would not work with this latent space I assume. How can I invert real images to the latent space of your approach? Do you have pre-trained inversion networks and if so, is it possible for you to share them? 

Thank you.

**Comment by RaymondJiangkw** [comment]
Hi, many thanks for your interest!

The inversion for NeRFFaceEditing is different from the StyleGAN2 (2D Generator) but is the same with EG3D (3D Generator), i.e. pivotal tuning inversion (PTI), which does not rely on any pre-trained inversion networks. If you would like to invert the real images, I recommend using the [newer implementation](https://github.com/IGLICT/NeRFFaceEditing/tree/updated) and resort to the open-source [projector](https://github.com/oneThousand1000/EG3D-projector) for inversion.

Specifically, I think replacing the network used in the original projector with our network (NeRFFaceEditing) will work. After obtaining the latent codes and fine-tuned generator, you can use the same practice for style transfer as in the notebook and remember to replace the generator and latent codes with yours.

If any additional questions for implementation, you are welcomed to raise them here. :)
